# -*- coding: utf-8 -*-
"""secao2_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROcOAyn4X7VbbD1MiO-C5AsbhzlLDPno

###Sintaxe Básica
"""

#Print funciona com aspas simples e duplas
print('Olá Mundo!')
print("Olá Mundo!")

#Comentário por linha e por bloco
'''
  Comentário
  por
  bloco
'''

"""###Operadores matemáticos"""

#Soma
print(4 + 4)

#Subtração
print(5 - 4)

#Multiplicação
print(2 * 4)

#Divisão
print(4 / 4)

#Exponenciação
print(2 ** 2)

#Resto de divisão
print(5 % 3)

#Divisão de chão
print(3 // 4)

#Priorização
print((2 + 2) * 2)

"""###Variáveis"""

#Variáveis de texto
Var_texto_01 = 'Olá mundo!'
Var_texto_02 = str('Olá mundão')

print(Var_texto_01 + '\n' + Var_texto_02)

#Variáveis numéricas
#Inteiro
Var_inteiro_01 = 10
Var_inteiro_02 = int(20)

print(f"{Var_inteiro_01} \n{Var_inteiro_02}")

#Float
Var_float_01 = 10.10
Var_float_02 = float(10.90)

print(f"{Var_float_01} \n{Var_float_02}")

#Booleano
Var_booleano_01 = True
Var_booleano_02 = False

print(f"{Var_booleano_01} \n{Var_booleano_02}")

"""###Tipos de dados"""

#Listas - criadas com colchetes []
#Acessa o dado pela posição e é mutável
Exemplo_lista_01 = [1, 2, 3, 4]
Exemplo_lista_02 = ['a', 'b', 'c', 'd']
Exemplo_lista_03 = [1, 'a', 2, 'b']

print(f"{Exemplo_lista_01} \n{Exemplo_lista_02} \n{Exemplo_lista_03}")

#Tuplas - criadas com parênteses ()
#Acessa o dado pela posição e é imutável
Exemplo_tupla_01 = (1, 2, 3, 4)
Exemplo_tupla_02 = ('a', 'b', 'c', 'd')
Exemplo_tupla_03 = (1, 'a', 2, 'b')

print(f"{Exemplo_tupla_01} \n{Exemplo_tupla_02} \n{Exemplo_tupla_03}")

#Dicionários = criados com chaves {}
#Acessa o dado pela chave criada e é mutável
Exemplo_dicionario_01 = {'chave_01': 1, 'chave_02': 2, 'chave_03': 3}
Exemplo_dicionario_02 = {'chave_01': 'a', 'chave_02': 'b', 'chave_03': 'c'}
Exemplo_dicionario_03 = {'chave_01': 1, 'chave_02': 'a', 'chave_03': 2, 'chave_04': 'b'}

print(f"{Exemplo_dicionario_01} \n{Exemplo_dicionario_02} \n{Exemplo_dicionario_03}")

"""###Nomeação de variáveis"""

#Declarar as variáveis em uma única linha de comando
Fruta_01, Fruta_02, Fruta_03 = 'Laranja', 'Maçã', 'Uva'

print(f"{Fruta_01} \n{Fruta_02} \n{Fruta_03}")

#Atribuir um valor à diversas variáveis
Fruta_01 = Fruta_02 = Fruta_03 = 'Melancia'

print(f"{Fruta_01} \n{Fruta_02} \n{Fruta_03}")

#Declarar usando uma Lista
Lista_frutas = ['Laranja', 'Maçã', 'Uva']
Fruta_01, Fruta_02, Fruta_03 = Lista_frutas

print(f"{Fruta_01} \n{Fruta_02} \n{Fruta_03}")

#Combinar variáveis
Nome = "Alana"
Sobrenome = "Sampaio"
Nome_completo = Nome + " " + Sobrenome

print(Nome_completo)

#Operar com operadores matemáticos
Investimento = 1000
Taxa_juros = 0.2
Juros = Investimento * Taxa_juros

print(Juros)

#Outro exemplo
Nome_01 = 'Alana'
Idade = str(25)
Nome_completo_01 = Nome_01 + ' ' + Idade + ' anos'

print(Nome_completo_01)

"""###Tipo de informação"""

'''
Text Type: str
Numeric Types: int, float, complex
Sequence Types: list, tuple, range
Mapping Type: dict
Set Types: set, frozenset
Boolean Type: bool
Binary Types: bytes, bytearray, memoryview
'''

String = str('Hello World')
Inteiro = int(10)
Float = float(100.5)
Complex = complex(1j)
List = list( ('Apple', 'Strawberry'))
Tuple = tuple( ('A', 'B'))
Range = range(6)
Dictionary = dict(name='Odemir', age=29)
Set = set(('A', 'B', 'C'))
Fronzet = frozenset( ('A', 'B', 'C'))
Boleano = bool(5)
Bytes = bytes(5)
ByteArray = bytearray(5)
Memoryview = memoryview(bytes(5))

from datetime import datetime
Data = datetime.today().date()


print(type(String))
print(type(Inteiro))

"""###Comando Round"""

#Usado para operações com números flutuantes, podendo selecionar quantos numeros decimais deseja para utilizar
Exemplo_round = 12.123456789
print(Exemplo_round)
print(round(Exemplo_round, 2))

"""###Comando Len"""

#A função len() retorna a quantidade de elementos de qualquer lista, tupla, dicionário, String
Exemplo_lista_04 = [True, 1, 12, 22, 'a', False, 'b']
print(len(Exemplo_lista_04))

Exemplo_String = 'Olá Mundo!'
print(len(Exemplo_String))

"""###Fatiamento de String"""

Exemplo_String_01 = 'Aprendendo Python para dados!'

print(Exemplo_String_01[0])
print(Exemplo_String_01[-1])
print(Exemplo_String_01[:10])
print(Exemplo_String_01[0:10])
print(Exemplo_String_01[-6:])

"""###Manipulação de String"""

Exemplo_String_02 = 'Olá Mundãoo!'
Meu_CPF = '12345678900'

#replace() - substitui uma determinada palavra ou trecho da String por outra
print(Exemplo_String_02.replace('Mundãoo', 'Mundo'))

#upper() - transforma todas as letras em maiúsculo
print(Exemplo_String_02.upper())

#lower() - transforma todas as letras em minúsculo
print(Exemplo_String_02.lower())

#capitalize() - transforma a primeira letra em maiúsculo
print(Exemplo_String_02.capitalize())

#startswith() - verifica se a String começa com um determinado conjunto de caracteres
print(Exemplo_String_02.startswith('Olá'))

#endswith() - verifica se a String termina com um determinado conjunto de caracteres
print(Exemplo_String_02.endswith('Mundãoo!'))

#count() - conta a quantidade de palavras/letras de uma String
print(Exemplo_String_02.count('o'))
print(Exemplo_String_02.count('Olá'))

#isdigit() - verifica se a String possui valor numérico
print(Meu_CPF.isdigit())

#isnumeric() - verifica se a String possui valor numérico
print(Meu_CPF.isnumeric())

#isalnum() - verifica se é alfanumérica
Exemplo_String_02 = 'OláMundo123'
print(Exemplo_String_02.isalnum())

#find() - localizar algo específico na String
Exemplo_String_02 = 'Está bastante calor hoje!'
print(Exemplo_String_02.find('calor')) #significa que a palavra calor começa a partir do 14 caracter e retorna -1 quando não existe

#strip() - remove espaço entre o fim e o começo entre as palavras
Exemplo_String_02 = ' Está bastante calor hoje! '
print(Exemplo_String_02.strip())

#split() - quebra a string
Exemplo_String_02 = 'Está bastante calor, hoje!'
Split = Exemplo_String_02.split()
print(Split)
print(Exemplo_String_02.split(','))
print(Split[1])

"""###Comando Input"""

#Usado para receber entrada do usuário
Nome_02 = input(str('Qual o seu nome? '))
print(Nome_02)

"""###Operadores de comparação"""

'''
'==' ( Igual a )
'!=' ( Diferente )
'>' ( Maior )
'<' ( Menor )
'>=' ( Maior igual )
'<=' ( Menor igual )
'''

print('8 é igual a 8: ', 8 == 8)
print('8 é diferente de 10: ', 8 != 10)
print('8 é maior a 6: ', 8 > 6)
print('3 é menor a 8: ', 3 < 8)
print('8 é maior ou igual a 8: ', 8 >= 8)
print('3 é menor ou igual a 8: ', 3 <= 8)

"""###Operadores lógicos"""

'''
And = 'and'
Ou = 'or'
Negação = 'not'
'''

print('8 é maior que 7 e 7 maior que 8:', 8 > 7 and 7 > 8 )
print('8 é maior que 7 e 7 menor que 8:', 8 > 7 and 7 < 8 )
print('8 é maior que 7 ou 7 menor que 8:', 8 == 7 or 7 == 8 )
print('8 é maior que 7 ou 7 menor que 8:', 8 > 7 or 7 > 8 )

"""###Operadores de identidade"""

#Os operadores comparam os objetos, mas não se são iguais e sim se estão alocados na mesma memória
#is - iguais
#is not - não iguais

String_01 = str('Olá Mundão')
String_02 = str('Olá Mundão')

print( String_01 is String_01 )
print( String_01 is String_02 )
print( String_01 == String_02 )
print( type(String_01) is type(String_02) )

"""###Operadores de associação"""

#Usados ​​para testar se uma sequência de caracteres ou numeros é apresentada em um objeto
#in - está presente
#not in - não está presente

Lista_frutas = ['Laranja', 'Uva', 'Melancia']

print('Laranja' in Lista_frutas)
print('Morango' in Lista_frutas)
print('Morango' not in Lista_frutas)

"""###Manipulando listas"""

Lista_vazia = []

#append() - Para adicionar um item ao final da lista
Lista_vazia.append('Melancia')
Lista_vazia.append('Uva')
Lista_vazia.append('Laranja')
print(Lista_vazia)

#len() - Calcular o tamanho da lista
print(len(Lista_vazia))

#[ ] - Acessar posições
print(Lista_vazia[0])
print(Lista_vazia[-1])
print(Lista_vazia[0:2])

#del() - Exlcuir um elemento
del Lista_vazia[1]
print(Lista_vazia)

#clear() - Limpar a lista
Lista_vazia.clear()
print(Lista_vazia)

#insert() - Para inserir um item de lista em um índice especificado
Lista_vazia.insert(0, 'Melancia')
Lista_vazia.insert(1, 'Uva')
Lista_vazia.insert(2, 'Laranja')
print(Lista_vazia)

#extend() - Anexar elementos de outra lista à lista atual
Lista_vazia_02 = ['Morango', 'Abacaxi']
Lista_vazia.extend(Lista_vazia_02)
print(Lista_vazia)

#remove() - Remove o item especificado
Lista_vazia.remove('Morango')
print(Lista_vazia)

#pop() - Remove o índice especificado
Lista_vazia.pop(0)
print(Lista_vazia)

#sort() - Ordenar os valores
Lista_ABC = ['a', 'c', 'z', 'd', 'y']
Lista_ABC.sort()
print(Lista_ABC)
Lista_ABC.sort(reverse=True)
print(Lista_ABC)

#copy() - Faz uma copia da Lista
Lista_ABC_02 = Lista_ABC.copy()
print(Lista_ABC_02)

#index() - Retorna o index do elemento da lista
print(Lista_ABC.index('d'))

"""###Pacote Datetime"""

import datetime
# Dia de Hoje
Dia_hoje = datetime.datetime.today().date()
print( f'Hoje é: {Dia_hoje} \n' )

# Construindo uma Data
Data = datetime.date(2020, 10, 1)
print( f'Construindo uma Data {Data} \n' )

# Acessando os atributos da DAta
Ano = Data.year
Mes = Data.month
Dia = Data.day
print(f'Hoje é dia {Dia} do mês {Mes} do ano de {Ano} \n')

# Operação
Intervalo = Data - Dia_hoje
print(f'Já ocorreu {Intervalo} dias \n' )

# Ajustando o formato
Novo_formato = Dia_hoje.strftime('%d/%m/%y')
print( f'Hoje é: {Novo_formato} \n' )

# Aumentar dias ou diminuir
print( f'Somando 30 dias, {Dia_hoje + datetime.timedelta(days = 30)}' )
print( f'Diminuindo 30 dias, {Dia_hoje - datetime.timedelta(days = 30)}' )

"""###Pacote Time"""

import time

print('Começando...')
time.sleep(5)
print('Finalizado após 5 segundos!')

#Capturando a hora
Hora_agora = time.localtime() #vem nesse formato - tm_year=2025, tm_mon=12, tm_mday=29, tm_hour=21, tm_min=19, tm_sec=58, tm_wday=0, tm_yday=363, tm_isdst=0
print(Hora_agora)
print(time.strftime('%d/%m/%Y, %H:%M:%S', Hora_agora))

#Convertendo String em time
Tempo_string = '20 December, 2025'
Conversao_data = time.strptime(Tempo_string, '%d %B, %Y')
print(Conversao_data)
print(time.strftime('%d/%m/%Y', Conversao_data))

"""###Pacote Math"""

import math

Tupla = (3, 2, 5, 8, 7, 9)

#Verifica número mínimo
print(min(Tupla))

#Verifica número máximo
print(max(Tupla))

#Transforma negativo em positivo
print(abs(-7.25))

#Calcula a potência
print(pow(2, 3))

#Calcula raiz quadrada
print(math.sqrt(81))

#Arredonda para mais
print(math.ceil(8.2))

#Arredonda para menos
print(math.floor(8.2))

#Retorna o pi
print(math.pi)

"""###Pacote Random"""

#Gera números pseudo-aleatórios
import random

Lista_01 = [2, 6, 5, 10, 15, 9]

#Seleciona um numero aleatorio da lista
print(random.choice(Lista_01))

#Seleciona uma letra aleatorio da String
Nome_03 = 'AlanaSampaio'
print(random.choice(Nome_03))

#Gera um número aleatório entre 0 e 1
print(random.random())

#Gera um número aleatório de um intervalo estipulado
print(random.randint(0, 10))

"""###Pacote Statistics"""

#Fornece funções para calcular estatísticas matemáticas de dados numéricos e interage com as listas
import statistics

Lista_01 = [2, 6, 5, 10, 15, 5, 9]

#Retirando média de uma lista
print(statistics.mean(Lista_01))

#Retirando mediana de uma lista
print(statistics.median(Lista_01))

#Retirando moda de uma lista
print(statistics.mode(Lista_01))

"""###Condição IF"""

Idade = 25

if Idade >= 18: #Se a idade for maior igual a 18 anos
  print('Maior de idade!')
else: #Caso contrário
  print('Menor de idade!')

if Idade > 18: #Se
  print('Maior que 18 anos!')
elif Idade == 18: #Senão
  print('Idade igual a 18 anos!')
else: #Caso contrário
  print('Menor que 18 anos!')

"""###Estrutura de repetição FOR"""

for QualquerCoisa in range(10):
  print(QualquerCoisa)

print('\n')

for QualquerCoisa in range(4, 10):
  print(QualquerCoisa)

print('\n')

for QualquerCoisa in range(1, 10, 2):
  print(QualquerCoisa)

print('\n')

#For com listas
Lista_paises = ['Brasil', 'Argentina', 'Uruguai', 'Chile', 'Paraguai', 'Bolivia', 'Equador',
                'Colombia', 'Suriname', 'Guiana', 'Guiana Francesa']
for QualquerNome in Lista_paises:
  print(QualquerNome)

print('\n')

#Para enumerar a lista
for num, Paises in enumerate(Lista_paises):
  print(num, Paises)

"""###Estrutura de repetição WHILE"""

